# Practice of string manipulation
# Don't use AI or other libraries for this assignment such as numpy or pandas.

def replace_extension(file_name: str, new_extension: str) -> str:
    # This function should replace the extension of the file name with the new extension and return the modified file name.
    # Fill in the code here
    
    return new_file_name
    
def generate_file_name() -> list[str]:
    # This function should generate a list of file names
    # The file names should be in the format of 
    # "date_birdID_trails_type.extension"
    # trials should be in the format of "T001", "T002", ..., "T006"
    # example 20250828_GG_T001_GRF

    file_names = []
    date_list = ["20250828", "20250902"]
    birdID_list = ["GG", "GB", "YB", "YY", "RY"]
    type_list = ["VID", "GRF"]
    
    return file_names


def filter_file_names()->list[str]:
    # This function should filter the file names generated by the 
    # generate_file_name function and return a list of file names that 
    # have "GRF" in their type and "T001" in their trails.
    # Fill in the code here
    file_names = generate_file_name()
    target_type = "GRF"
    
    return filtered_file_names