# Practice of string manipulation
# Don't use AI or other libraries for this assignment such as numpy or pandas.

def replace_extension(file_name: str, new_extension: str) -> str:
    # This function should replace the extension of the file name with the new extension and return the modified file name.
    # Fill in the code here'
    file_name_list = file_name.split('.')
    new_file_name = file_name.replace(file_name_list[-1], new_extension)

    return new_file_name
    
def generate_file_name() -> list[str]:
    # This function should generate a list of file names
    # The file names should be in the format of 
    # "date_birdID_trails_type.extension"
    # trials should be in the format of "T001", "T002", ..., "T006"
    # example 20250828_GG_T001_GRF

    file_names = []
    date_list = ["20250828", "20250902"]
    birdID_list = ["GG", "GB", "YB", "YY", "RY"]
    type_list = ["VID", "GRF"]
    for date in date_list:
        for birdID in birdID_list:
            for type in type_list:
                for i in range(1, 7):
                    print(f"{date}_{birdID}T00{i}_{type}")
    
    return file_names


def filter_file_names()->list[str]:
    # This function should filter the file names generated by the 
    # generate_file_name function and return a list of file names that 
    # have "GRF" in their type and "T001" in their trails.
    # Fill in the code here
    file_names = generate_file_name()
    target_type = "GRF"
    new_file_name = file_names.split("_")
    filtered_file_names = []
    for file_name in file_names:
        if (new_file_name[-1] == "GRF") and (new_file_name[1] == "T001"):
            filtered_file_names.append(file_name)
   
    return filtered_file_names
